language: python

# ===== Linux ======
dist: xenial
python:
  - 3.7
matrix:
  include:
    - name: "Python 3.7 on linux"
      os: linux
      language: python
      before_install:
          - pip install -U pip
          - pip install .
          - cd Projects/project_2_packages/paddleboat
      script: python -m unittest -v
